apiVersion: v1
kind: Secret
metadata:
  name: backup-pgpass-secret
  namespace: __NAMESPACE__
stringData:
  .pgpass: "__DB_HOST__:__DB_PORT__:*:__DB_USER__:__DB_PASSWORD__"

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-cronjob
  namespace: __NAMESPACE__
spec:
  schedule: "__CRON_SCHEDULE__"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup-runner
            image: __IMAGE_NAME__
            args:
              - "-h"
              - "__DB_HOST__"
              - "-p"
              - "__DB_PORT__"
              - "-u"
              - "__DB_USER__"
              - "-d"
              - "/backups"
              - "-l"
              - "/dev/stdout"
            volumeMounts:
              - name: backup-storage
                mountPath: /backups
              - name: pgpass-secret-volume
                mountPath: /etc/pgpass-secret
            env:
              - name: PGPASSFILE
                value: /etc/pgpass-secret/.pgpass
          volumes:
            - name: backup-storage
              hostPath:
                path: __BACKUP_PATH__
                type: DirectoryOrCreate
            - name: pgpass-secret-volume
              secret:
                secretName: backup-pgpass-secret
